# Generated by Django 4.2.3 on 2023-07-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_video_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='is_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_current_time',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_number',
            field=models.IntegerField(default=0),
        ),
    ]
