# Generated by Django 4.2.3 on 2023-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_video_is_watched_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_current_time',
            field=models.IntegerField(default=0),
        ),
    ]
