# Generated by Django 4.2.3 on 2023-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video_url_alter_video_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
